# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
common: &common
  adapter: postgresql
  username: managedshowings
  password: managedshowings

development:
  <<: *common
  database: managedshowings_development

test:
  <<: *common
  database: managedshowings_test

production:
  <<: *common
  database: managedshowings_production

